version: '3'
services:
  strapi:
    build: .
    env_file: .env
    external_links:
      - postgres13master
    networks:
      - intern
      - web
    ports:
      - '1337:1337'
networks:
  intern:
      external: true
  web:
      external: true