version: '3'
services:
  strapi:
    build:
      context: ./
      dockerfile: Dockerfile_dev
    command: yarn develop
    external_links:
      - postgres13master
    networks:
      - intern
      - web
    ports:
      - '1337:1337'
    volumes:
      - ../.env:/app/.env
networks:
  intern:
      external: true
  web:
      external: true