version: '3'
services:
  strapi:
    build: .
    command: yarn start
    external_links:
      - postgres13master
    networks:
      - intern
      - web
    expose:
      - 1337
networks:
  intern:
      external: true
  web:
      external: true